---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start and Enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy hello world page
  template:
    src: nginx.conf.j2
    dest: /var/www/html/index.html


